// GENERATED by Invoke-ApeVending.ps1 -- do not edit.
// Decision: infeasible -- no candidate family can reach 64 vCPUs
using '../../bicep/ape-apply.bicep'

param region = 'eastus'
param writesRequired = [

]
