<#
    .SYNOPSIS
    Stage 2 of subscription vending, the Bicep way: read, decide, then hand a
    .bicepparam to Bicep to write.

    .DESCRIPTION
    Bicep cannot read quota state -- see docs/GUIDE.md -- so on this path
    the reading and the deciding happen in PowerShell and Bicep only writes.
    The Terraform path does all three in Terraform; both are held to the same
    answers by conformance/scenarios.

    .EXAMPLE
    ./Invoke-ApeVending.ps1 -SubscriptionId $subId

    Evaluates the decision and writes ape-apply.bicepparam. Nothing is deployed.

    .EXAMPLE
    ./Invoke-ApeVending.ps1 -SubscriptionId $subId -Deploy

    Also runs the Bicep deployment.
#>
[CmdletBinding()]
param(
    # From stage 1: avm-ptn-sub-vending's `subscription_id` output.
    [Parameter(Mandatory)][string]$SubscriptionId,

    # The vending request both stages read.
    [string]$IntakeFile = (Join-Path $PSScriptRoot '..' 'vending-stage-2' 'intake.example.yaml'),

    [string]$ParamFile = (Join-Path $PSScriptRoot 'ape-apply.bicepparam'),

    # Off by default so the decision can be reviewed before anything is written.
    [switch]$Deploy
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = Join-Path $PSScriptRoot '..' '..'
Import-Module (Join-Path $repo 'powershell' 'ApeRead.psm1') -Force
Import-Module (Join-Path $repo 'powershell' 'ApePlacement.psm1') -Force

# The intake is YAML because that is what the request pipeline produces. Bicep
# cannot read YAML either, which is another reason the decision happens here.
if (-not (Get-Module -ListAvailable powershell-yaml)) {
    throw 'The powershell-yaml module is required to read the intake. Install-Module powershell-yaml'
}
Import-Module powershell-yaml -Force
$intake = ConvertFrom-Yaml (Get-Content $IntakeFile -Raw)
$compute = $intake.compute

# Optional intake fields are genuinely absent rather than null, and StrictMode
# throws on a missing key, so read them defensively.
function Opt($map, $key) {
    if ($map -is [System.Collections.IDictionary] -and $map.Contains($key)) { return $map[$key] }
    return $null
}

$request = @{
    region                 = $compute.region
    vcpus                  = $compute.vcpus
    category               = Opt $compute 'category'
    architecture           = Opt $compute 'architecture'
    burstable              = Opt $compute 'burstable'
    confidential_computing = Opt $compute 'confidential_computing'
    family                 = Opt $compute 'family'
    family_allowlist       = Opt $compute 'family_allowlist'
    placement              = Opt $compute 'placement'
    environment            = $intake.subscription.environment

    # A vended subscription is by definition new, and new subscriptions cannot
    # deploy growth-restricted series at all.
    new_subscription       = $true
}

# Business rules belong to the platform team, not the requester, so they live
# here rather than in the intake.
$rules = @(
    @{
        name            = 'devtest stays off GPU and stays small'
        environments    = @('devtest')
        family_denylist = @('standardNCSv3Family', 'standardNVSv4Family')
        max_vcpus       = 32
    }
)

Write-Host "Reading $($compute.region) for $SubscriptionId ..." -ForegroundColor Cyan
$state = Get-ApeState -SubscriptionId $SubscriptionId -Region $compute.region -KnowledgeDir (Join-Path $repo 'knowledge')

$decision = Get-ApePlacement -Request $request -Pool $state.pool -SkuAccess $state.sku_access -Rules $rules

Write-Host ''
Write-Host ("  status   : {0}" -f $decision.status)
Write-Host ("  reason   : {0}" -f $decision.reason)
Write-Host ("  category : {0}" -f $decision.category)
Write-Host ("  family   : {0}" -f $decision.family)
Write-Host ("  writes   : {0}" -f @($decision.writes_required).Count)
if ($decision.access.remediation) {
    Write-Host ("  remedy   : {0}" -f $decision.access.remediation) -ForegroundColor Yellow
}
Write-Host ''

# The handoff to Bicep. `writes_required` is already the shape ape-apply.bicep
# takes, so this is a serialisation and nothing more -- no second opinion about
# what should happen gets formed here.
$writes = @($decision.writes_required | ForEach-Object {
        "    { scope: '$($_.scope)', name: '$($_.name)', limit: $($_.limit) }"
    })

$content = @"
// GENERATED by Invoke-ApeVending.ps1 -- do not edit.
// Decision: $($decision.status) -- $($decision.reason)
using '../../bicep/ape-apply.bicep'

param region = '$($compute.region)'
param writesRequired = [
$($writes -join "`n")
]
"@

Set-Content -Path $ParamFile -Value $content -Encoding utf8
Write-Host "Wrote $ParamFile" -ForegroundColor Green

# A refused quota write fails the deployment on purpose: a vended subscription
# that cannot run its workload is a failure, not a caveat. See
# modules/ape-apply/README.md for the three refusal codes, none retryable.
if ($decision.status -in @('blocked_by_region', 'not_ready', 'blocked_by_lifecycle', 'blocked_by_access', 'blocked_by_rule', 'infeasible')) {
    Write-Host 'Nothing to deploy: the decision did not produce a workable placement.' -ForegroundColor Yellow
    exit 1
}

if (-not $Deploy) {
    Write-Host 'Re-run with -Deploy to apply it.' -ForegroundColor DarkGray
    exit 0
}

Write-Host 'Deploying ...' -ForegroundColor Cyan
New-AzSubscriptionDeployment `
    -Location $compute.region `
    -TemplateParameterFile $ParamFile `
    -Name ("ape-quota-{0}" -f (Get-Date -Format 'yyyyMMddHHmmss'))
